available_text_models: ["gpt-3.5-turbo", "gpt-4", "gpt-3.5-turbo-16k-0613"]

info:
  gpt-3.5-turbo:
    type: chat_completion
    name: gpt-3.5-turbo
    description: gpt-3.5-turbo <b>НЕ</b> поддерживает плагины.

    price_per_1000_input_tokens: 0.000
    price_per_1000_output_tokens: 0.000

    scores:
      Smart: 3
      Fast: 5
 #     Cheap: 5

  gpt-4:
    type: chat_completion
    name: gpt-4
    description: GPT-4 <b>самая умная</b> и самая передовая модель в мире. Но она медленнее чем ChatGPT. Лучший выбор для <b>комплексных</b> интеллектуальных задач.

    price_per_1000_input_tokens: 0.00
    price_per_1000_output_tokens: 0.00

    scores:
      Smart: 5
      Fast: 2
 #     Cheap: 2

  gpt-3.5-turbo-16k-0613:
    type: chat_completion
    name: gpt-3.5-turbo-16k-0613
    description: gpt-3.5-turbo-16k-0613 поддерживает плагины. 

    price_per_1000_input_tokens: 0.00
    price_per_1000_output_tokens: 0.00

    scores:
      Smart: 3
      Fast: 5
#      Cheap: 3

  whisper:
    type: audio
    price_per_1_min: 0.000
